apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "homebridge.fullname" . }}
  labels:
{{ include "homebridge.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homebridge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homebridge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: "America/New_York"
          - name: HOMEBRIDGE_CONFIG_UI
            value: "1"
          - name: HOMEBRIDGE_CONFIG_UI_PORT
            value: "8080"
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: "/homebridge"
              name: homebridge-pvc
          {{ end -}}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: homekit-http
              containerPort: 51826
              protocol: TCP
            - name: homekit-udp
              containerPort: 51826
              protocol: UDP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 1800
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 1800
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.persistence.enabled }}
      volumes:
      - name: homebridge-pvc
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "docker-registry.fullname" . }}{{- end }}
    {{ end -}}
      {{- if .Values.image.imagePullSecretEnabled }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
      {{ end -}}