apiVersion: v1
kind: Service
metadata:
  name: {{ template "homebridge.fullname" . }}
  labels:
{{ include "homebridge.labels" . | indent 4 }}
spec:
  type: {{ .Values.webService.type }}
  ports:
    - port: {{ .Values.webService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "homebridge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}